Refactor breath bubbles
PrismarineJS/prismarine-web-client pull request #265
Opened 2021-12-28 05:07 UTC by u9g

2021-12-28 15:56 UTC, u9g commented
https://streamable.com/ubm7cw

2021-12-28 16:20 UTC, rom1504 commented
Looks good
CI failing

2021-12-28 16:20 UTC, AwesomestCode requested changes
Code looks good for the most part but it seems to be a bit buggy. Testing on a lake, when oxygen is exhausted (where you're already losing HP) it keeps flashing between full and to empty. Also, when you go up to get air sometimes you'll still have oxygen flashing, not sure why.

2022-01-20 16:47 UTC, rom1504 commented
old, re-open if you want to finish

2022-01-20 16:56 UTC, rom1504 commented
still old, but can stay open if you want to fix it

2022-01-22 16:11 UTC, rom1504 commented on lib/menus/components/breath_bar.js
> +  static get properties = {
you're missing the parenthesis after properties

2022-08-07 15:08 UTC, rom1504 commented
too old, please re-open if you want to finish

2022-08-07 15:08 UTC, closed without merging