Fix chat messages
PrismarineJS/prismarine-web-client pull request #272
Opened 2022-01-14 07:35 UTC by KalmeMarq

![image](https://user-images.githubusercontent.com/55203647/149469109-11ad92e5-68e1-4d27-861b-298687318eeb.png)

2022-01-14 14:10 UTC, AwesomestCode requested changes
Can we move the README changes to a separate PR?

2022-01-14 14:14 UTC, KalmeMarq commented
wdym

2022-01-20 16:31 UTC, rom1504 commented on lib/chat.js
> +      console.log(fullmessage)
this looks like forgotten debugging, can you remove it ?

2022-01-20 16:32 UTC, rom1504 commented
left a comment, otherwise lgtm

2022-01-20 18:26 UTC, KalmeMarq commented
![image](https://user-images.githubusercontent.com/55203647/150399106-d7104f4d-efbc-4433-8ffa-a48019b4aea3.png)

2022-01-20 19:38 UTC, merged